name: Run Screenplay Examples

on: [pull_request, push]

jobs:
  run-examples:
    runs-on: ubuntu-18.04
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error
    continue-on-error: ${{ matrix.continueOnError }}

    strategy:
      matrix:
        continueOnError: [true]
        timeoutMinutes: [ 5 ]
        node: [ 10 ]
        folder: [
          'jest',
          'mocha',
          'simple'
        ]

    name: Example ${{ matrix.folder }} on node ${{ matrix.node }}

    defaults:
        run:
            shell: bash
            working-directory: integration-examples/${{ matrix.folder }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

    #   - run: pwd
    #   - run: ls -al

      - uses: microsoft/playwright-github-action@v1

      - name: restore npm cache
        uses: actions/cache@master
        with:
          path: |
            integration-examples/${{ matrix.folder }}/node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('integration-examples/${{ matrix.folder }}/package-lock.json') }}

      - run: npm install
      - name: Run tests with Screenplay
        run: xvfb-run --auto-servernum npm test

      - name: Cleanup xvfb pidx
        uses: bcomnes/cleanup-xvfb@v1

      - name: Upload .screenplay dir
        uses: actions/upload-artifact@v1
        if: ${{ always() }}
        with:
          name: screenplay-${{ matrix.folder }}
          path: integration-examples/${{ matrix.folder }}/.screenplay
